### ISSUE TITLE
Getting "'Crashlytics/Crashlytics.h' file not found" on SMXCrashlytics.m

### ISSUE THREAD

**Issue by dorongutman** [corymsmith/react-native-fabric#17]
I've updated from 0.0.2 to 0.1.0, followed all steps and I'm getting the following error when trying to compile:

`'Crashlytics/Crashlytics.h' file not found` on line 2 in file `SMXCrashlytics.m`.

I have the same import in my AppDelegate.m file without any problems or error.
If I go back to 0.0.2 (and removed the SMXCrashlytics library) everything works fine.

I'm using CocoaPods and that's how Fabric and Crashlytics are installed

**Comment by DougBanksPersonal** [comment]
+1
Just installed today, having the same problem.

**Comment by dovfrank** [comment]
+1
Same here.

**Comment by sibeliusseraphini** [comment]
try to reinstall Fabric

**Comment by dovfrank** [comment]
Tried again on iOS, seems to work. I guess I did not complete the Crashlytics configuration correctly on the first time.
Thanks!

**Comment by ultralame** [comment]
i had the same issue. i'm using cocoapods and fabric was installed correctly. here's how i got it to work:

- in xcode project select SMXCrashlytics.xcodeproj under Libraries
- go to Build Settings -> Search Paths -> Header Search Paths
- add `$(SRCROOT)/../../../ios/Pods/Headers/Public/Crashlytics` as a non-recursive path

now open your xcworkspace and it should build. your relative path might be different from mine, and maybe there's a better way to do this. i'm still new to ios development.

@corymsmith thanks for the awesome module! any thoughts on making this change that will fix things for cocoapods users? not sure if my solution is general enough to merge. for now i'll have to switch to a fork or react-native-fabric so my team doesn't have to go through this process whenever they do a fresh npm install

**Comment by faceyspacey** [comment]
what if you're not using cocoapods? ..or how would you use cocoapods with this?

**Comment by faceyspacey** [comment]
oh my bad, i didn't even install crashlytics itself. ..probably should be in the docs for other newbs. ...gotten all the way to the activation step at this point. it hangs for me. probably need to put in some credentials or something.

**Comment by faceyspacey** [comment]
...yea for anyone else out there expecting a more standard react-native iOS install process, the gotchas were:

- install crashlytics separately (i recommend starting with that) by just going to their site and following their directions verbatim
- then follow the react-native install directions in this repo (if you do this first and try to run it, you will run into additional problems)
- then make sure you follow the final steps here to get your app delegate file triggering crashyltics:

https://fabric.io/kits/ios/crashlytics/install

**Comment by corymsmith** [comment]
@faceyspacey It's the second line in the README, if you have some thoughts on how we can make that more clear I'd gladly change the Readme or accept a PR that clarifies that since alot of the issues seem to be caused by Fabric not being installed first.

**Comment by abhaytalreja** [comment]
Just 1 thing, after struggling a bit, cocoapods pod file comes with the default setting for swift it has a line 'use_frameworks!`
Please comment this line for react-native as it is based of objC.

![image](https://cloud.githubusercontent.com/assets/1915902/16242059/a7823b8a-37be-11e6-9548-6b21d64e4b8a.png)

**Comment by npomfret** [comment]
Reinstalled everything, downloaded the latest version of the app, followed all the instructions (not using pods).  Still getting `'Crashlytics/Crashlytics.h' file not found`.  Any other ideas?

Using rn 0.29

**Comment by npomfret** [comment]
My problem was that I was trying to put the frameworks in a `frameworks` directory on disk, looks like that's just not possible for some reason.

**Comment by jerson** [comment]
if you use framework must add this 

$(SRCROOT)/../../../ios/Pods/Crashlytics/iOS

in xcode project select SMXCrashlytics.xcodeproj under Libraries
go to Build Settings -> Search Paths ->  Framework search Paths

and add it

**Comment by wootwoot1234** [comment]
Had the same problem (I just didn't install everything in the right order) so I made some changes to the readme for future users.  Here's the pull request https://github.com/corymsmith/react-native-fabric/pull/63

**Comment by farzadab** [comment]
Well, I had similar problem (well, the error was in my `AppDelegate.m` not in `SMXCrashlytics.m`), so here's how I fixed it:
I'm using `pods` and know nothing about iOS. I randomly found out that `pods` creates a `Pods.xcodeproj` (inside `ios/Pods` folder). So I dragged it and added it to `Libraries` inside the `Project Navigator` (the first tab in the left pane of XCode) and the problem was solved.


(P.S: Sorry for being a newbie.)

**Comment by iddan** [comment]
Still getting this on a clean installation of RN

**Comment by sunny635533** [comment]
With latest master，i still have that error in swift project，through added it  Without CocoaPods.
1~ , add `pod 'Fabric'   pod 'Crashlytics'` in your podfile, 
2~, drag SMXCrashlytics.xcodeproj to your project and choose " create folders referrences " 
Then you can build pretty!
