### ISSUE TITLE
'Crashlytics/Crashlytics.h' file not found at update component

### ISSUE THREAD

**Issue by luisfuertes** [corymsmith/react-native-fabric#76]
I update component version and now on iOS:
`/myProject/node_modules/react-native-fabric/ios/SMXCrashlytics/SMXCrashlytics.m:2:9: 'Crashlytics/Crashlytics.h' file not found`

In `SMXCrashlytics.m`fail `#import <Crashlytics/Crashlytics.h>` 

In SMXcrashlytics project, `Header Search Paths` have:  `$(SRCROOT)/../../../ios/Pods/Headers/Public/Crashlytics`

But in `Headers` i dont have Crashlytics, but i have it on my Podfile and in `/ios/Pods/Crashlytics`

I think i must  add the correct `Framework Search Paths`.

**Comment by ljhender** [comment]
Did you ever get this resolved? having the same issue on xcode 8

**Comment by ljhender** [comment]
Fixed this by disabling SMXCrashlytics from the link binary with libraries, installing crashlytics via their mac app, then re enabling / adding the SMXCrashlytics library.

**Comment by luisfuertes** [comment]
@ljhender can you check if you now have Headers  in `$(SRCROOT)/../../../ios/Pods/Headers/Public/Crashlytics`

And what path have in `Framework Search Path`and `Header Search Paths`? Thanks!

**Comment by luisfuertes** [comment]
I remove `libSMXCrashlytics.a` and reinstall Crashlytics from Mac App, but continue with error

**Comment by atlanteh** [comment]
Happens to me to! I'm stuck for hours on this with no luck :(

**Comment by vonovak** [comment]
also had this issue; as ljhender points out, you first need to install Fabric from their website, and only then install this library.

**Comment by atlanteh** [comment]
Can u please provide a small guide as to how to do that? I've just started using mac..How do i get their "mac app"? In Crashlytics site they seem to only have the pod option..no option to install manually..

**Comment by rcugut** [comment]
See this previous issue that is a duplicate for this one:  #17 

Read below for a conclusion of how to fix this (I wish I had this distilled when I had the problem myself, since it took me a while to figure things out):

There are 2 scenarios based on your Podfile: you have `use_frameworks!` enabled -or- disabled (i.e. commented out).

### First, regardless of what scenario you're in

In your XCode project select `Libraries/SMXCrashlytics.xcodeproj` , and go to Target's  "Build Settings". Then:

### if you have `use_frameworks!` enabled in Podfile

in `Framework search Paths`, add:

`$(SRCROOT)/../../../ios/Pods/Crashlytics/iOS`

=> You're DONE

### if you do NOT have `use_frameworks!` enabled in Podfile

in `Header Search Paths`

`$(SRCROOT)/../../../ios/Pods/Headers/Public/Crashlytics`  with non-recursive set

=> You're DONE

**Comment by jacob-meacham** [comment]
I opened a PR ( #84 ) that is an alternative solution to the problem and does not require editing the xcodeproj.

**Comment by corymsmith** [comment]
I'd prefer something like Jacob's PR, I've been pretty busy lately so haven't had a chance to test out a bunch of this

**Comment by arthurnn** [comment]
@rcugut 's solution worked: `$(SRCROOT)/../../../ios/Pods/Crashlytics/iOS`

**Comment by corymsmith** [comment]
This should be fixed by #92, if not please re-open

**Comment by fabriziomoscon** [comment]
I had this problem as well this issue is related to #17 #81 #84 
I solved by:
- uninstalling everything.
- installing Fabric with the Fabric desktop app and Fabric and Crashlytics pods
- making sure that Fabric works on ios before touching the react-native installation
- then I used the latest master ( @corymsmith can we push it on npm? )
- follow the readme instruction (pods version) comment out #use_frameworks
- compile

You should also receive an email from Fabric confirming the new ios project has been added

This was definitely the most difficult module I had to integrate on ios and RN. If anybody knows how to make it easier to integrate please comment.

**Comment by abcde1499** [comment]
@rcugut 's solution still failed for me :(

My RN version is 0.44

Here's my Podfile
`use_frameworks!

target ‘dm_app’ do
    pod 'SwiftyJSON', '3.1.4'
    pod 'Charts', '3.0.1'
    pod 'Firebase/Core', '4.0.0'
    pod 'Firebase/Messaging'
    pod 'Fabric'
    pod 'Crashlytics'
end
    
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
end
`

![2017-08-14 2 12 39](https://user-images.githubusercontent.com/3325816/29260215-19036d0c-80fb-11e7-9ff5-60a772a56f14.png)
![2017-08-14 2 13 21](https://user-images.githubusercontent.com/3325816/29260222-1d933bae-80fb-11e7-9ad0-bdf6ebc2f7e5.png)


Anyone still facing the same problem now?

**Comment by Simba14** [comment]
+1

**Comment by sunny635533** [comment]
+1，stiil has that  error when through to  link binary with libraries
